# use / to create a website server locally
baseurl = "https://inianv.github.io/"
languageCode = "en-us"
title = "Bitwise Insights"
theme = "ghostwriter"
copyright = "Inian Vasanth"
googleAnalytics = ""
enableGitInfo = true

[[privacy.disqus]]
    disable = true

[[Params.Author]]
    name = "Inian Vasanth"
    profile = "https://inianv.github.io/about/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Bitwise Insights"
    description = "Building intuition, one byte at a time"
    email = "inianvasanth@proton.me"
    github = "https://github.com/inianv"
    linkedin = "https://www.linkedin.com/in/inian-vasanth-20806b76"
    gitlab = "https://gitlab.com/inianvasanth"
    stackoverflow = "https://stackoverflow.com/users/5291015/inian"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    readingTime = false
    readingTimeText = ""

[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 2

[[menu.main]]
    name = "All Posts"
    url = '/archive/'
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[markup]
    footnoteReturnLinkContents = "↩"

[markup.highlight]
    style = "dracula"
    tabWidth = 2

[markup.tableOfContents]
    startLevel = 1
    endLevel = 2
    ordered = true

[pagination]
    pagerSize = 7

# “date” usually means (article’s file) creation date i.e. when the idea was
# first convinced, “lastmod” almost always comes from Git, set “pushlishDate”
# when publishing.  Being explicit is usually better; fallbacks below:
[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    publishDate = ["publishDate", "date"]
    lastmod = [":git", "lastmod", "date", "publishDate"]
